##**Aula 1 - Fazendo leitura de arquivos CSV**

Dados:
- https://github.com/alura-cursos/Pandas/blob/main/superstore_data.csv
- https://github.com/alura-cursos/Pandas/blob/main/superstore_data_ponto_virgula.csv

###**Lendo arquivos CSV**

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'

In [ ]:
dados = pd.read_csv(url)

In [ ]:
dados.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'

In [ ]:
dados_ponto_virgula = pd.read_csv(url_2)

In [ ]:
dados_ponto_virgula.head()

  Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

###**Parâmetros da função read_csv**
Documentação: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

In [ ]:
dados_ponto_virgula = pd.read_csv(url_2, sep = ';')

In [ ]:
dados_ponto_virgula

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [ ]:
dados_primeiras_linhas = pd.read_csv(url,nrows=5)
dados_primeiras_linhas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
dados_selecao = pd.read_csv(url, usecols=[0,1,4])
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

###**Escrevendo arquivos CSV**

Documentação: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [ ]:
dados_selecao.to_csv('clientes_mercado.csv')

In [ ]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')
clientes_mercado

      Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

In [ ]:
dados_selecao.to_csv('dados_mercado.csv', index=False)

In [ ]:
dados_mercado = pd.read_csv('/content/dados_mercado.csv')
dados_mercado

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

##**Aula 2 - Utilizando planilhas**

Dados: https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx

###**Lendo arquivos Excel**

In [ ]:
import pandas as pd

In [ ]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [ ]:
dados_co2 = pd.read_excel(url)

In [ ]:
dados_co2.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

###**Parâmetros da função read_excel**

Documentação: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

In [ ]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [ ]:
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fontes = pd.read_excel(url, sheet_name='fontes')

In [ ]:
fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [ ]:
intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols= 'A:D')

In [ ]:
intervalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
intervalo_2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols= 'A:D', nrows=10)

In [ ]:
intervalo_2

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

###**Escrevendo arquivos Excel**

In [ ]:
percapita.to_excel('co2_percapita.xlsx', index=False)

In [ ]:
pd.read_excel('/content/co2_percapita.xlsx')

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

###**Lendo dados do Google Planilhas**

link da planilha: https://docs.google.com/spreadsheets/d/1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog/edit?usp=sharing

In [ ]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
dados_co2_sheets = pd.read_csv(url)

In [ ]:
dados_co2_sheets

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,36.096.739.276,14.506.973.805,12.242.627.935,7.144.928.128,1.507.923.185,391.992.176,302.294.047,4.749.682
63100,Global,WLD,2018,36.826.506.600,14.746.830.688,12.266.016.285,7.529.846.784,1.569.218.392,412.115.746,302.478.706,4.792.753
63101,Global,WLD,2019,37.082.558.969,14.725.978.025,12.345.653.374,7.647.528.220,1.617.506.786,439.253.991,306.638.573,4.775.633
63102,Global,WLD,2020,35.264.085.734,14.174.564.010,11.191.808.551,7.556.290.283,1.637.537.532,407.583.673,296.301.685,4.497.423
63103,Global,WLD,2021,37.123.850.352,14.979.598.083,11.837.159.116,7.921.829.472,1.672.592.372,416.525.563,296.145.746,4.693.699

In [ ]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'emissoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
percapita_sheets = pd.read_csv(url_percapita)

In [ ]:
percapita_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
fontes_sheets = pd.read_csv(url_fontes)

In [ ]:
fontes_sheets.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

##**Aula 3 - Manipulando arquivos JSON**

Dados:
- https://github.com/alura-cursos/Pandas/blob/main/pacientes.json
- https://github.com/alura-cursos/Pandas/blob/main/pacientes_2.json

###**Lendo arquivos JSON**

In [ ]:
import pandas as pd

In [ ]:
dados_pacientes = pd.read_json('/content/pacientes.json')

FileNotFoundError: ignored

In [ ]:
dados_pacientes

In [ ]:
dados_pacientes_2 = pd.read_json('/content/pacientes_2.json')

In [ ]:
dados_pacientes_2

###**Normalizando arquivos JSON**

In [ ]:
df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])

In [ ]:
df_normalizado

###**Escrevendo arquivos JSON**

In [ ]:
df_normalizado.to_json('historico_pacientes_norm.json')

In [ ]:
pd.read_json('/content/historico_pacientes_norm.json')

##**Aula 4 - Lendo dados em HTML e XML**

Dados: https://github.com/alura-cursos/Pandas/blob/main/filmes_wikipedia.html

###**Lendo páginas web**

In [ ]:
import pandas as pd

In [ ]:
dados_html = pd.read_html('/content/filmes_wikipedia.html')

In [ ]:
dados_html

In [ ]:
type(dados_html)

In [ ]:
len(dados_html)

In [ ]:
top_filmes = dados_html[1]

In [ ]:
top_filmes

###**Escrevendo arquivos HTML**

In [ ]:
top_filmes.to_html('top_filmes.html')

In [ ]:
pd.read_html('/content/top_filmes.html')

In [ ]:
top_filmes.to_csv('top_filmes_1998', index=False)

In [ ]:
dados = pd.read_csv('/content/top_filmes_1998')
dados.head()

###**Lendo/escrevendo arquivos XML**
Dados: https://github.com/alura-cursos/Pandas/blob/main/imdb_top_1000.xml

In [ ]:
import pandas as pd

In [ ]:
dados_imdb = pd.read_xml('/content/imdb_top_1000.xml')

In [ ]:
dados_imdb.head(3)

In [ ]:
dados_imdb.to_xml('filmes_imdb.xml')

##**Aula 5 - Trabalhando com banco de dados**

Dados: https://github.com/vqrca/Pandas/blob/main/clientes_banco.csv

###**Criando um banco de dados local**

In [1]:
pip install --upgrade 'sqlalchemy<2.0'

Collecting sqlalchemy<2.0
  Downloading SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.7 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.0) (2.0.2)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.19
    Uninstalling SQLAlchemy-2.0.19:
      Successfully uninstalled SQLAlchemy-2.0.19
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.49 which is incompatible.
Successfully installed sqlalchemy-1.4.49

In [3]:
import sqlalchemy

In [4]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [5]:
engine = create_engine('sqlite:///:memory:')

###**Escrevendo em um banco de dados**

In [6]:
import pandas as pd

In [7]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [8]:
dados = pd.read_csv(url)

In [9]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [10]:
dados.to_sql('clientes', engine, index=False)

438463

In [11]:
inspector = inspect(engine)

In [12]:
print(inspector.get_table_names())

['clientes']

###**Lendo uma consulta SQL**

In [13]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [14]:
query

'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [15]:
empregados = pd.read_sql(query, engine)

In [16]:
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [17]:
pd.read_sql_table("clientes",engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [18]:
empregados.to_sql('empregados', con=engine, index=False)

226059

In [19]:
pd.read_sql_table('empregados', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [20]:
pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade',
                                                 'Rendimento_anual'])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

###**Atualizando um banco de dados**

In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(query, engine)

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
    conn.execute(query)

In [ ]:
pd.read_sql_table('clientes', engine)

In [ ]:
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    conn.execute(query)

In [ ]:
pd.read_sql_table('clientes', engine)